service: powerdash

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 600
  environment:
    SS_AUTH_ID: ${env:SS_AUTH_ID}
    SS_AUTH_TOKEN: ${env:SS_AUTH_TOKEN}

package:
  exclude:
    - test_data/**
  include:
    - service.json

functions:
  getZip:
    handler: handler.handleGetZip
    events:
      - http:
          path: zip
          method: get
          cors: true
