org: powerthepolls
app: powerdash
service: powerdash

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 600
  environment:
    PTP_HOST: ${env:PTP_HOST}
    PTP_DB: ${env:PTP_DB}
    PTP_USER: ${env:PTP_USER}
    PTP_PASS: ${env:PTP_PASS}
    SECRET_KEY: ${env:SECRET_KEY}
    BASE_SHEET: ${env:BASE_SHEET}
    TEMPLATE_BASE: ${env:TEMPLATE_BASE}
    TEMPALTE_PII: ${env:TEMPALTE_PII}

package:
  exclude:
    - test_data/**
  include:
    - service.json

functions:
  updatePartner:
    handler: handler.handleUpdatePartner
    events:
      - http:
          path: sheet
          method: post

  updatePartners:
    handler: handler.handleUpdatePartners
    events:
      - schedule: rate(10 minutes)
